### ISSUE TITLE
Redirects not handled with private access

### ISSUE THREAD

**Issue by ohmybrew** [ohmybrew/Basic-Shopify-API#16]
Using private access, redirects (Location header) in Shopify do not include private credentials.

So when accessing discount lookup for example, it will redirect to a login page.

This is now fixed in master with #900bc0b.

It also includes an error handler for CLIENT errors only (400 types).

Tests need to be adjusted and written to account for this now... will update.

**Comment by ohmybrew** [comment]
Solved in v5.0.0

**Comment by demoskp** [comment]
Hi sorry to bother again, I tried it with the new code and I still don't seem to get the location header, it's not returned in the response again. Am I missing a step?

**Comment by ohmybrew** [comment]
It does a complete redirect and gets the code for you, no location header will exist at the point. Its following base Guzzle config.

**Comment by demoskp** [comment]
This is supposed to get the discount code location. What code does it get for me and where is it stored?

On 26 Feb 2019 14:21, Tyler King <notifications@github.com> wrote:

It does a complete redirect and gets the code for you, no location header will exist at the point. Its following base Guzzle config.

**Comment by ohmybrew** [comment]
No since Guzzle default redirects, and with the new fix to adjust that redirect URL, it will now properly work.

https://imgur.com/a/dIQ6tOw

It will simply split out the discount code.

If it does not be found, you will see this: https://imgur.com/a/zwVkqX9

**Comment by demoskp** [comment]
I'll try it again today and see how it goes, thanks though.

On 26 Feb 2019 14:32, Tyler King <notifications@github.com> wrote:

No since Guzzle default redirects, and with the new fix to adjust that redirect URL, it will now properly work.

https://imgur.com/a/dIQ6tOw

It will simply split out the discount code.

If it does not be found, you will see this: https://imgur.com/a/zwVkqX9

**Comment by demoskp** [comment]
When it doesn't find the code it returns exactly what you said which is "+"errors": "Not Found""

However when I try to get an existing code accessing the body return null.

I am not sure what the issue is in my case, I updated the BasicShopifyAPI.php file so I am not sure if there is something I am missing here.

**Comment by ohmybrew** [comment]
What's the request you're sending out, what do you mean a code that exists? I try with a code that exists, and returns fine On Feb. 26, 2019 18:06, demoskp <notifications@github.com> wrote:When it doesn't find the code it returns exactly what you said which is "+"errors": "Not Found""
However when I try to get an existing code accessing the body return null.
I am not sure what the issue is in my case, I updated the BasicShopifyAPI.php file so I am not sure if there is something I am missing here.

**Comment by demoskp** [comment]
$shop->api()->request('GET' , '/admin/discount_codes/lookup.json?code=example')->body;

What I mean is if a discount code actually exists on the store and I do the lookup it return null on the body. If that discount code does not exist on that store then I get the errors": "Not Found""  as the body which is great.

The issue is when it should return the the discount code, the price rule and then rest like your example but in my case it doesn't.

**Comment by ohmybrew** [comment]
Try doing:$shop->api()->request('GET' , '/admin/discount_codes/lookup.json', ['code' => 'example'])->body;On Feb. 26, 2019 18:38, demoskp <notifications@github.com> wrote:$shop->api()->request('GET' , '/admin/discount_codes/lookup.json?code=example')->body;
What I mean is if a discount code actually exists on the store and I do the lookup it return null on the body. If that discount code does not exist on that store then I get the errors": "Not Found""  as the body which is great.
The issue is when it should return the the discount code, the price rule and then rest like your example but in my case it doesn't.

**Comment by demoskp** [comment]
Tried that as well, it still returns null for the body.

**Comment by ohmybrew** [comment]
Found the issue! Requires some rework... reopening.

**Comment by ohmybrew** [comment]
v5.1.0 should have this all fixed up now.

**Comment by demoskp** [comment]
Works like a charm, thanks a lot mate.

On 27 Feb 2019 20:16, Tyler King <notifications@github.com> wrote:

v5.1.0 should have this all fixed up now.

**Comment by ohmybrew** [comment]
Good to hear!
